In [6]:
import tensorflow as tf
import numpy as np

In [7]:
n_features = None
n_classes = None
n_hidden = None

features = tf.placeholder(tf.float32, [None, n_features])
labels = tf.placeholder(tf.float32, [n_classes])

hidden_weights = tf.Variable(tf.truncated_normal([n_features, n_hidden]))
hidden_bias = tf.Variable(tf.zeros([n_hidden]))

output_weights = tf.Variable(tf.truncated_normal([n_hidden, n_classes]))
output_bias = tf.Variable(tf.truncated_normal([n_classes]))

init = global_variable_initializer()

TypeError: Expected binary or unicode string, got None

In [ ]:
hidden_layer = tf.add(tf.matmul(features, hidden_weights), hidden_bias)
hidden_layer = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_layer, output_weights), output_bias)

In [8]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

output = None
hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[1.0, 2.0, 3.0, 4.0], [-1.0, -2.0, -3.0, -4.0], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model
init = tf.global_variables_initializer()

hidden_layer = tf.add(tf.matmul(features, weights[0]), biases[0])
hidden_layer = tf.nn.relu(hidden_layer)

output = tf.add(tf.matmul(hidden_layer, weights[1]), biases[1])
with tf.Session() as session:
    session.run(init)
    print(session.run(output))
    

# TODO: Print session results


[[  5.11000013   8.44000053]
 [  0.           0.        ]
 [ 24.01000214  38.23999786]]


In [9]:
def create_placeholders(n_features, n_classes):
    """
    Create placeholders for features and labels
    
    Since we're passing bathces through the network and not single input data points, 
    labels and features placeholders will hold None value for number of rows (first dimension)
    """
    features = tf.placeholder(tf.float32, [None, n_features]) #each input data is a row vector!!!
    labels = tf.placeholder(tf.float32, [None, n_classes])
    return feaures, labels

def create_weights_biases(n_features, n_classes, n_hidden_nodes):
    """
    Creates tf variables for weights and biases
    """
    weights_biases = []
    
    weight_hidden = tf.Variable(tf.truncated_normal([n_features, n_hidden_nodes]))
    bias_hidden = tf.Variable(tf.zeros([n_hidden_nodes]))
    weights_biases.append((wegiht_hidden, bias_hidden))
    
    weight_output = tf.Variable(tf.truncated_normal([n_hidden, n_classes]))
    bias_output = tf.Variable(tf.zeros([n_classes]))
    weights_biases.append((weight_output, bias_output))
    
    return weights_biases
    

In [15]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('.', one_hot=True, reshape=False)
# the data is already one_hot encoded and bathced

import tensorflow as tf

# Parameters
learning_rate = 0.001
training_epochs = 20
batch_size = 128
display_step = 1

n_input = 784
n_classes = 10

# the focus here is on the architecture of multilayer neural netowkrs, not parameter tunning

n_hidden_layer = 256
# size of the hidden layer (number of units, nodes), also known as the width of a layer

# Weights and Biases
# storing weights and biases in dictionaries
weights = {'hidden_layer':tf.Variable(tf.truncated_normal([n_input, n_hidden_layer])),
          'out':tf.Variable(tf.random_normal([n_hidden_layer, n_classes]))}

biases = {'hidden_layer':tf.Variable(tf.random_normal([n_hidden_layer])),
         'out':tf.Variable(tf.random_normal([n_classes]))}

# Creating Input
x = tf.placeholder("float", [None, 28, 28, 1])
y = tf.placeholder("float", [None, n_classes])

x_flat = tf.reshape(x, [-1, n_input])
# reshapes the input data, (28pixels x 28pizels x 1channel) to a row vector


# Hidden layer with RELU activation
layer_1 = tf.add(tf.matmul(x_flat, weights['hidden_layer']), biases['hidden_layer'])
layer_1 = tf.nn.relu(layer_1)

# output layer with linear activation
logits = tf.add(tf.matmul(layer_1, weights['out']), biases['out'])

# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# variables initializer
init = tf.global_variables_initializer()

# Launch the graph in a session:
with tf.Session() as sess:
    sess.run(init)
    
    #training cycle:
    for epoch in range(training_epochs):
        # getting the unmber of betches
        total_batch = int(mnist.train.num_examples/batch_size)
        
        #loop over all batches 
        for i in range(total_batch):
            # retrieve a batch
            batch_x, batch_y = mnist.train.next_batch(batch_size)
            
            # Run optimization op (backpropagation) and cost op (get loss value)
            sess.run(optimizer, feed_dict={x:batch_x, y:batch_y})
            
            
            

Extracting .\train-images-idx3-ubyte.gz
Extracting .\train-labels-idx1-ubyte.gz
Extracting .\t10k-images-idx3-ubyte.gz
Extracting .\t10k-labels-idx1-ubyte.gz


# Save and Restore TensorFlow Models

Training a model can take hours. But once you close your TensorFlow session, you lose all the trained weights and biases. If you were to reuse the model in the future, you would have to train it all over again!

Fortunately, TensorFlow gives you the ability to save your progress using a class called tf.train.Saver. This class provides the functionality to save any tf.Variable to your file system.

## Saving Variables

In [25]:
import tensorflow as tf

# the file path to save the data
save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()
#WE NEED TO CREATE A TENSORFLOW OBJECT SAVER()

with tf.Session() as sess:
    # Initialize all the variables
    sess.run(tf.global_variables_initializer())
    
    # Show the values of weights and bias
    print('Weights: ')
    print(sess.run(weights))
    print('Bias: ')
    print(sess.run(bias))
    
    # Save the model
    saver.save(sess, save_file) # send in the session and the file path
    # saving the 

Weights: 
[[-1.43450093  0.32465461 -1.29993463]
 [ 0.9825421   0.53475571 -1.54516721]]
Bias: 
[ 0.58077872  0.91625226  0.14777227]


## Loading Variables

In [26]:
# REmove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()
# create a saver object again. It'll have a method to restore the variables

with tf.Session() as sess:
    # Load the weights and bias
    saver.restore(sess, save_file)
    # There's no need to call global_variables_initializer since saver.restore()
    # alerady sets all TensorFlow variables.

    # Show the values of weights and bias
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

Weight:
[[-0.12411158 -1.58582056  0.12832981]
 [ 0.72183931  0.01716107 -0.14314321]]
Bias:
[-1.92029905 -0.596479    0.87187147]


In [31]:
# Remove previous Tensors and Operations
tf.reset_default_graph()

from tensorflow.examples.tutorials.mnist import input_data
import numpy as np

learning_rate = 0.001
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
mnist = input_data.read_data_sets('.', one_hot=True)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
cost = tf.reduce_mean(\
    tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)\
    .minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

Extracting .\train-images-idx3-ubyte.gz
Extracting .\train-labels-idx1-ubyte.gz
Extracting .\t10k-images-idx3-ubyte.gz
Extracting .\t10k-labels-idx1-ubyte.gz


In [32]:
import math

save_file = './train_model.ckpt'
batch_size = 128
n_epochs = 100

saver = tf.train.Saver()

# Launch the graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # Training cycle
    for epoch in range(n_epochs):
        total_batch = math.ceil(mnist.train.num_examples / batch_size)

        # Loop over all batches
        for i in range(total_batch):
            batch_features, batch_labels = mnist.train.next_batch(batch_size)
            sess.run(
                optimizer,
                feed_dict={features: batch_features, labels: batch_labels})

        # Print status for every 10 epochs
        if epoch % 10 == 0:
            valid_accuracy = sess.run(
                accuracy,
                feed_dict={
                    features: mnist.validation.images,
                    labels: mnist.validation.labels})
            print('Epoch {:<3} - Validation Accuracy: {}'.format(
                epoch,
                valid_accuracy))

    # Save the model
    saver.save(sess, save_file)
    print('Trained Model Saved.')

Epoch 0   - Validation Accuracy: 0.1371999979019165
Epoch 10  - Validation Accuracy: 0.3142000138759613
Epoch 20  - Validation Accuracy: 0.4323999881744385
Epoch 30  - Validation Accuracy: 0.5091999769210815
Epoch 40  - Validation Accuracy: 0.5752000212669373
Epoch 50  - Validation Accuracy: 0.621999979019165
Epoch 60  - Validation Accuracy: 0.65420001745224
Epoch 70  - Validation Accuracy: 0.6779999732971191
Epoch 80  - Validation Accuracy: 0.6955999732017517
Epoch 90  - Validation Accuracy: 0.7089999914169312
Trained Model Saved.


In [33]:
saver = tf.train.Saver()

# Launch the graph
with tf.Session() as sess:
    saver.restore(sess, save_file)
    # use .restore() method from saver object, sending in the session and the file
    # name as arguments
    
    test_accuracy = sess.run(accuracy, feed_dict={features: mnist.test.images,labels: mnist.test.labels})
    
print('Test Accuracy: {}'.format(test_accuracy))

Test Accuracy: 0.7282000184059143


In [35]:
import tensorflow as tf

# Remove the previous weights and bias
tf.reset_default_graph()

save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Save Weights: {}'.format(weights.name))
print('Save Bias: {}'.format(bias.name))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.save(sess, save_file)

# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
bias = tf.Variable(tf.truncated_normal([3]))
weights = tf.Variable(tf.truncated_normal([2, 3]))

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Load Weights: {}'.format(weights.name))
print('Load Bias: {}'.format(bias.name))

with tf.Session() as sess:
    # Load the weights and bias - ERROR
    saver.restore(sess, save_file)

Save Weights: Variable:0
Save Bias: Variable_1:0
Load Weights: Variable_1:0
Load Bias: Variable:0


InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [2,3] rhs shape= [3]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@Variable_1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1, save/RestoreV2_1)]]

Caused by op 'save/Assign_1', defined at:
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-0e1713b00e31>", line 29, in <module>
    saver = tf.train.Saver()
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1051, in __init__
    self.build()
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 675, in build
    restore_sequentially, reshape)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 414, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\lucas\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [2,3] rhs shape= [3]
	 [[Node: save/Assign_1 = Assign[T=DT_FLOAT, _class=["loc:@Variable_1"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Variable_1, save/RestoreV2_1)]]


You'll notice that the name properties for weights and bias are different than when you saved the model. This is why the code produces the "Assign requires shapes of both tensors to match" error. The code saver.restore(sess, save_file) is trying to load weight data into bias and bias data into weights.

In [37]:
import tensorflow as tf

tf.reset_default_graph()

save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]), name='weights_0')
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Save Weights: {}'.format(weights.name))
print('Save Bias: {}'.format(bias.name))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver.save(sess, save_file)

# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
bias = tf.Variable(tf.truncated_normal([3]), name='bias_0')
weights = tf.Variable(tf.truncated_normal([2, 3]) ,name='weights_0')

saver = tf.train.Saver()

# Print the name of Weights and Bias
print('Load Weights: {}'.format(weights.name))
print('Load Bias: {}'.format(bias.name))

with tf.Session() as sess:
    # Load the weights and bias - No Error
    saver.restore(sess, save_file)

print('Loaded Weights and Bias successfully.')

Save Weights: weights_0:0
Save Bias: bias_0:0
Load Weights: weights_0:0
Load Bias: bias_0:0
Loaded Weights and Bias successfully.


# Regularization

When building models, it is really hard to build one that learns the ammount of features desirable from your training set. This means that your model might weither learn less patterns than needed, so it won't perform good in either the training and validation sets, or will learn more features than desirable, which overfits the training data, and your model will perform poorly on new data given in. To prevent both, it is a common practice to build a larger model than needed, and then use tchniques to prevent overfitting tha data.

One of this techniques is Early Termination, which looks at the performance of the validation set and stops the training as soons as it stops improving.

Another Technique is L2 Regularization, which adds another term to the loss function, the l2 of the weight matrix. 

## Dropout

Your network can never rely on any given activation to be present in the data, since they may be randomly shutoff. This means that the same input won't propagate the same activations troughout the network, so the net is forced to learn a redundant representation for everything, to make sure that at least some of the information remains.

Tensorflow provides the tf.nn.dropout() function

In [38]:
keep_prob = tf.placeholder(tf.float32)

hidden_layer = tf.add(tf.matmul(features, weights[0]), bias[0])
hidden_layer = tf.nn.relu(hidden_layer)
hidden_layer = tf.nn.dropout(hidden_layer, keep_prob)

logits = tf.add(tf.matmul(hidden_layer, weights[1]), bias[1])

ValueError: Tensor("strided_slice:0", shape=(3,), dtype=float32) must be from the same graph as Tensor("Placeholder:0", shape=(?, 784), dtype=float32).

keep_prob allows you to adjust the number of units to drop. In order to compensate for dropped units, tf.nn.dropout() multiplies all units that are kept (i.e. not dropped) by 1/keep_prob.

Remember: keep_prob should be set to 1.0 when evaluating validation accuracy

In [39]:
# Solution is available in the other "solution.py" tab
import tensorflow as tf

hidden_layer_weights = [
    [0.1, 0.2, 0.4],
    [0.4, 0.6, 0.6],
    [0.5, 0.9, 0.1],
    [0.8, 0.2, 0.8]]
out_weights = [
    [0.1, 0.6],
    [0.2, 0.1],
    [0.7, 0.9]]

# Weights and biases
weights = [
    tf.Variable(hidden_layer_weights),
    tf.Variable(out_weights)]
biases = [
    tf.Variable(tf.zeros(3)),
    tf.Variable(tf.zeros(2))]

# Input
features = tf.Variable([[0.0, 2.0, 3.0, 4.0], [0.1, 0.2, 0.3, 0.4], [11.0, 12.0, 13.0, 14.0]])

# TODO: Create Model with Dropout
keep_prob = tf.placeholder(tf.float32)

layer_1 = tf.add(tf.matmul(features, weights[0]), biases[0])
layer_1 = tf.nn.relu(layer_1)
layer_1 = tf.nn.dropout(layer_1, keep_prob)

output = tf.add(tf.matmul(layer_1, weights[1]), biases[1])
# TODO: Print logits from a session
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print(sess.run(output, feed_dict={keep_prob:0.5}))



[[  7.67999935  15.05999947]
 [  0.71400005   0.91800004]
 [ 43.30000305  48.15999985]]
